def _(s):
    return s


COUNTRY_MAP = {
    "ar": _("Argentina"),
    "at": _("Austria"),
    "au": _("Australia"),
    "be": _("Belgium"),
    "bg": _("Bulgaria"),
    "br": _("Brazil"),
    "ca": _("Canada"),
    "ch": _("Switzerland"),
    "cl": _("Chile"),
    "cn": _("China Mainland"),
    "co": _("Colombia"),
    "cr": _("Costa Rica"),
    "cz": _("Czech Republic"),
    "de": _("Germany"),
    "dk": _("Denmark"),
    "ec": _("Ecuador"),
    "ee": _("Estonia"),
    "eg": _("Egypt"),
    "es": _("Spain"),
    "es-ca": _("Catalonia"),
    "fi": _("Finland"),
    "fr": _("France"),
    "gr": _("Greece"),
    "gt": _("Guatemala"),
    "hk": _("Hong Kong"),
    "hr": _("Croatia"),
    "hu": _("Hungary"),
    "ie": _("Ireland"),
    "il": _("Israel"),
    "igo": _("IGO"),
    "in": _("India"),
    "it": _("Italy"),
    "jo": _("Jordan"),
    "jp": _("Japan"),
    "kr": _("South Korea"),
    "lu": _("Luxembourg"),
    "mk": _("Macedonia"),
    "mt": _("Malta"),
    "mx": _("Mexico"),
    "my": _("Malaysia"),
    "ng": _("Nigeria"),
    "nl": _("Netherlands"),
    "no": _("Norway"),
    "nz": _("New Zealand"),
    "pe": _("Peru"),
    "ph": _("Philippines"),
    "pl": _("Poland"),
    "pr": _("Puerto Rico"),
    "pt": _("Portugal"),
    "ro": _("Romania"),
    "rs": _("Serbia"),
    "scotland": _("UK: Scotland"),
    "se": _("Sweden"),
    "sg": _("Singapore"),
    "si": _("Slovenia"),
    "sk": _("Slovak Republic"),
    "th": _("Thailand"),
    "tw": _("Taiwan"),
    "ua": _("Ukraine"),
    "ug": _("Uganda"),
    "uk": _("UK: England & Wales"),
    "us": _("United States"),
    "ve": _("Venezuela"),
    "vn": _("Vietnam"),
    "za": _("South Africa")}


LANG_MAP = {
    "af": _("Afrikaans"),
    "ar": _("Arabic"),
    "as": _("Assamese"),
    "ast": _("Asturian"),
    "az": _("Azerbaijani"),
    "be": _("Belarusian"),
    "bg": _("Bulgarian"),
    "bn": _("Bengali"),
    "ca": _("Catalan"),
    "cs": _("Czech"),
    "da": _("Danish"),
    "de": _("German"),
    "el": _("Greek"),
    "en": _("English"),
    "en_CA": _("English (CA)"),
    "en_GB": _("English (GB)"),
    "en_HK": _("English (Hong Kong)"),
    "en_SG": _("English (Singapore)"),
    "en_US": _("English (US)"),
    "eo": _("Esperanto"),
    "es": _("Spanish"),
    "es_AR": _("Spanish (AR)"),
    "es_CL": _("Spanish (CL)"),
    "es_CO": _("Spanish (CO)"),
    "es_EC": _("Spanish (Ecuador)"),
    "es_ES": _("Spanish (Spain)"),
    "es_GT": _("Spanish (Guatemala)"),
    "es_MX": _("Spanish (MX)"),
    "es_PE": _("Spanish (PE)"),
    "et": _("Estonian"),
    "eu": _("Basque"),
    "fa": _("Persian"),
    "fi": _("Finnish"),
    "fr": _("French"),
    "fr_CA": _("French (CA)"),
    "ga": _("Irish"),
    "gl": _("Galician"),
    "he": _("Hebrew"),
    "hi": _("Hindi"),
    "hr": _("Croatian"),
    "hu": _("Hungarian"),
    "hy": _("Armenian"),
    "id": _("Indonesian"),
    "is": _("Icelandic"),
    "it": _("Italian"),
    "ja": _("Japanese"),
    "ka": _("Georgian"),
    "kk": _("Kazakh"),
    "ko": _("Korean"),
    "lt": _("Lithuanian"),
    "lv": _("Latvian"),
    "mk": _("Macedonian"),
    "ml": _("Malayalam"),
    "mn": _("Mongolian"),
    "ms": _("Malay"),
    "nl": _("Dutch"),
    "no": _("Norwegian"),
    "nso": _("Northern Sotho"),
    "oci_ES": _("Aranese"),
    "pl": _("Polish"),
    "pt": _("Portuguese"),
    "pt_BR": _("Portuguese (BR)"),
    # "pt_PT": _("Portuguese (Portugal)"),
    "ro": _("Romanian"),
    "ru": _("Russian"),
    "si_LK": _("Sinhala"),
    "sl": _("Slovenian"),
    "sr": _("Serbian"),
    "sr_LATN": _("Serbian (Latin)"),
    "st": _("Sotho"),
    "sv": _("Swedish"),
    "ta": _("Tamil"),
    "te": _("Telugu"),
    "th": _("Thai"),
    "tr": _("Turkish"),
    "uk": _("Ukranian"),
    "ur": _("Urdu"),
    "vi": _("Vietnamese"),
    "zh": _("Chinese"),
    "zh_CN": _("Chinese"),
    "zh_HK": _("Chinese (Hong Kong)"),
    "zh_TW": _("Chinese (Taiwan)"),
    "zu": _("Zulu")}


LICENSE_NAME_MAP = {
    "GPL": _("GPL"),
    "LGPL": _("LGPL"),
    "by": _("Attribution"),
    "by-nc": _("Attribution-NonCommercial"),
    "by-nc-nd": _("Attribution-NonCommercial-NoDerivs"),
    "by-nc-sa": _("Attribution-NonCommercial-ShareAlike"),
    "by-nd": _("Attribution-NoDerivs"),
    "by-nd-nc": _("Attribution-NoDerivs-NonCommercial"),
    "by-sa": _("Attribution-ShareAlike"),
    "mark": _("Public Domain Mark"),
    "nc": _("NonCommercial"),
    "nc-sa": _("NonCommercial-ShareAlike"),
    "nc-sampling+": _("NonCommercial Sampling Plus"),
    "nd": _("NoDerivs"),
    "nd-nc": _("NoDerivs-NonCommercial"),
    "publicdomain": _("Public Domain"),
    "sa": _("ShareAlike"),
    "sampling": _("Sampling"),
    "sampling+": _("Sampling Plus")}


CHARACTERISTIC_TITLE_MAP = {
  "by": _("Attribution"),
  "nc": _("Noncommercial"),
  "nd": _("No Derivative Works"),
  "sa": _("Share Alike")}


CHARACTERISTIC_BRIEF_DESC_MAP = {
    "by": _(
        "You must attribute the work in the manner specified by the author "
        "or licensor (but not in any way that suggests that they endorse you "
        "or your use of the work)."),
    "na": _(
        "You may not use this work to advertise for or promote anything but "
        "the work you create from it."),
    "nc": _("You may not use this work for commercial purposes."),
    "nd": _("You may not alter, transform, or build upon this work."),
    "no": _(
        "You may not perform, display, or distribute copies of this whole "
        "work for any purpose."),
    "sa": _(
        "If you alter, transform, or build upon this work, you may "
        "distribute the resulting work only under the same or similar "
        "license to this one."),
    "sa_bysa30": _(
        "If you alter, transform, or build upon this work, you may "
        "distribute the resulting work only under the same, similar "
        "or a compatible license.")}
