# Generated by Django 2.2.13 on 2020-07-15 13:38

# Third-party
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.URLField(
                        help_text="The license's unique identifier, e.g."
                        " 'http://creativecommons.org/licenses/by-nd/2.0/br/'",
                        unique=True,
                    ),
                ),
                (
                    "license_code",
                    models.CharField(
                        help_text=(
                            "shorthand representation for which class of"
                            " licenses this falls into.  E.g. 'by-nc-sa', or"
                            " 'MIT', 'nc-sampling+', 'devnations', ..."
                        ),
                        max_length=40,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "jurisdiction_code",
                    models.CharField(blank=True, default="", max_length=9),
                ),
                (
                    "creator_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="E.g. http://creativecommons.org",
                    ),
                ),
                (
                    "license_class_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="E.g. http://creativecommons.org/license/",
                    ),
                ),
                (
                    "deprecated_on",
                    models.DateField(
                        help_text="if set, the date on which this license was"
                        " deprecated",
                        null=True,
                    ),
                ),
                ("permits_derivative_works", models.BooleanField()),
                ("permits_reproduction", models.BooleanField()),
                ("permits_distribution", models.BooleanField()),
                ("permits_sharing", models.BooleanField()),
                ("requires_share_alike", models.BooleanField()),
                ("requires_notice", models.BooleanField()),
                ("requires_attribution", models.BooleanField()),
                ("requires_source_code", models.BooleanField()),
                ("prohibits_commercial_use", models.BooleanField()),
                ("prohibits_high_income_nation_use", models.BooleanField()),
                (
                    "is_based_on",
                    models.ForeignKey(
                        blank=True,
                        help_text="another license that this one is based on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_of",
                        to="licenses.License",
                    ),
                ),
                (
                    "is_replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="another license that has replaced this one",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replaces",
                        to="licenses.License",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="another license that this is the"
                        " translation of",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_of",
                        to="licenses.License",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseLogo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="")),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="licenses.License",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslatedLicenseName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'."
                        " Case-sensitive?",
                        max_length=7,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Translated name of license", max_length=250
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="licenses.License",
                    ),
                ),
            ],
            options={
                "unique_together": {("license", "language_code")},
            },
        ),
        migrations.CreateModel(
            name="LegalCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="E.g. http://creativecommons.org/licenses/by-nd/3.0/rs/legalcode.sr-Cyrl",  # noqa: E501
                        unique=True,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'."
                        " Case-sensitive?",
                        max_length=7,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_codes",
                        to="licenses.License",
                    ),
                ),
            ],
        ),
    ]
