# Generated by Django 2.2.20 on 2021-07-07 21:30

# Third-party
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("licenses", "0001_initial"),
        ("licenses", "0002_auto_20210706_1522"),
        ("licenses", "0003_auto_20210707_1153"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        help_text="The license's unique identifier, e.g. "
                        "'https://creativecommons.org/licenses/by-nd/2.0/br/'",
                        unique=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="shorthand representation for which class of"
                        " licenses this falls into. E.g. 'by-nc-sa', or 'MIT',"
                        " 'nc-sampling+', 'devnations', ...",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "jurisdiction_code",
                    models.CharField(blank=True, default="", max_length=9),
                ),
                (
                    "creator_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="E.g. https://creativecommons.org",
                        verbose_name="Creator URL",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'licenses' or 'publicdomain'",
                        max_length=13,
                    ),
                ),
                (
                    "deprecated_on",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="if set, the date on which this license was"
                        " deprecated",
                        null=True,
                    ),
                ),
                (
                    "permits_derivative_works",
                    models.BooleanField(default=None),
                ),
                ("permits_reproduction", models.BooleanField(default=None)),
                ("permits_distribution", models.BooleanField(default=None)),
                ("permits_sharing", models.BooleanField(default=None)),
                ("requires_share_alike", models.BooleanField(default=None)),
                ("requires_notice", models.BooleanField(default=None)),
                ("requires_attribution", models.BooleanField(default=None)),
                ("requires_source_code", models.BooleanField(default=None)),
                (
                    "prohibits_commercial_use",
                    models.BooleanField(default=None),
                ),
                (
                    "prohibits_high_income_nation_use",
                    models.BooleanField(default=None),
                ),
                (
                    "is_based_on",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="another license that this one is based on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_of",
                        to="licenses.License",
                    ),
                ),
                (
                    "is_replaced_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="another license that has replaced this one",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replaces",
                        to="licenses.License",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="another license that this is the"
                        " translation of",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_of",
                        to="licenses.License",
                    ),
                ),
                ("deed_only", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-version", "unit", "jurisdiction_code"],
            },
        ),
        migrations.CreateModel(
            name="LegalCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'."
                        " Case-sensitive? This is the language code used by"
                        " CC, which might be a little different from the"
                        " Django language code.",
                        max_length=8,
                    ),
                ),
                (
                    "html_file",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTML file we got this from",
                        max_length=300,
                        verbose_name="HTML file",
                    ),
                ),
                (
                    "translation_last_update",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="The last_updated field from Transifex for"
                        " this translation",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="License title in this language, e.g."
                        " 'Atribución/Reconocimiento 4.0 Internacional'",
                        max_length=112,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True, default="", verbose_name="HTML"
                    ),
                ),
                (
                    "legal_code_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Legal Code URL"
                    ),
                ),
                (
                    "deed_url",
                    models.URLField(unique=True, verbose_name="Deed URL"),
                ),
                (
                    "plain_text_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Plain text URL"
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_codes",
                        to="licenses.License",
                    ),
                ),
            ],
            options={
                "ordering": ["license", "language_code"],
            },
        ),
        migrations.CreateModel(
            name="TranslationBranch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=40)),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'."
                        " Case-sensitive? This is a CC language code, which"
                        " might differ from Django.",
                        max_length=8,
                    ),
                ),
                (
                    "last_transifex_update",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Time when last updated on Transifex.",
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "legal_codes",
                    models.ManyToManyField(to="licenses.LegalCode"),
                ),
            ],
            options={
                "verbose_name_plural": "translation branches",
            },
        ),
    ]
