# Generated by Django 2.2.13 on 2020-06-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='identifier',
            new_name='license_code',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='default_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.Language'),
        ),
    ]
