# Generated by Django 2.2.13 on 2020-07-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='identifier',
            new_name='license_code',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='default_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.Language'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='url',
            field=models.URLField(help_text='E.g. http://creativecommons.org', unique=True),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='url',
            field=models.URLField(help_text='E.g. http://creativecommons.org/international/at/', unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'. Case-sensitive?", max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='licenseclass',
            name='url',
            field=models.URLField(help_text='E.g. http://creativecommons.org/license/', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='legalcode',
            unique_together={('url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='translatedlicensename',
            unique_together={('license', 'language')},
        ),
    ]
