# Generated by Django 2.2.20 on 2021-07-06 19:22

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translationbranch",
            old_name="legalcodes",
            new_name="legal_codes",
        ),
        migrations.RenameField(
            model_name="legalcode",
            old_name="license_url",
            new_name="legal_code_url",
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="legal_code_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Legal Code URL"
            ),
        ),
    ]
