# Generated by Django 2.2.20 on 2021-07-07 15:53

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_auto_20210706_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="deed_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="license",
            name="deprecated_on",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="if set, the date on which this license was"
                " deprecated",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="unit",
            field=models.CharField(
                help_text="shorthand representation for which class of"
                " licenses this falls into. E.g. 'by-nc-sa', or 'MIT',"
                " 'nc-sampling+', 'devnations', ...",
                max_length=20,
            ),
        ),
    ]
