# Generated by Django 2.2.13 on 2020-06-29 18:27
from django.core.management import call_command
from django.db import migrations


def import_from_rdf(apps, schema_editor):
    call_command("import_index_rdf")


def clear_out(apps, schema_editor):
    License = apps.get_model("licenses.license")
    License.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_auto_20200629_1227"),
    ]

    operations = [migrations.RunPython(import_from_rdf, clear_out)]
