# Generated by Django 3.2.5 on 2021-07-28 17:47

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_auto_20210715_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalcode",
            name="language_code",
            field=models.CharField(
                help_text="Django language tag (lowercase RFC5646 language"
                " tag)",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="translationbranch",
            name="language_code",
            field=models.CharField(
                help_text="Django language tag (lowercase RFC5646 language"
                " tag)",
                max_length=15,
            ),
        ),
    ]
