# Generated by Django 2.2.13 on 2020-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_auto_20200902_1302"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationBranch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=40)),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="E.g. 'en', 'en-ca', 'sr-Latn', or 'x-i18n'. Case-sensitive?",
                        max_length=8,
                    ),
                ),
                (
                    "last_transifex_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name=(
                            "Time when translations related to this branch were last updated on "
                            "Transifex that we know of.  If we see a newer last_update in Transifex, "
                            "we need to update the git branch from the latest translation files, and "
                            "then update this value to the most recent update time of those files."
                        ),
                    ),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=False,
                        verbose_name=(
                            "There should only be one record per branch name with complete=False. "
                            "There could be many with complete=True."
                        ),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="legalcode",
            name="translation_last_update",
            field=models.DateTimeField(
                default=None,
                help_text="The last_updated field from Transifex for this translation",
                null=True,
            ),
        ),
        migrations.DeleteModel(name="LicenseLogo",),
        migrations.AddField(
            model_name="translationbranch",
            name="legalcodes",
            field=models.ManyToManyField(to="licenses.LegalCode"),
        ),
    ]
