# Generated by Django 3.2.5 on 2021-08-06 16:19

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0005_auto_20210728_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalcode",
            name="language_code",
            field=models.CharField(
                help_text="Django langauge code (lowercase IETF language tag)",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="translationbranch",
            name="language_code",
            field=models.CharField(
                help_text="Django langauge code (lowercase IETF language tag)",
                max_length=15,
            ),
        ),
    ]
