# Generated by Django 2.2.13 on 2020-11-05 19:04

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0009_auto_20201029_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalcode",
            name="deed_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legalcode",
            name="license_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legalcode",
            name="plain_text_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
