# Generated by Django 2.2.20 on 2021-05-22 00:29

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0011_auto_20201111_1256"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalcode",
            options={"ordering": ["license", "language_code"]},
        ),
        migrations.RemoveField(
            model_name="license",
            name="license_class_url",
        ),
        migrations.AddField(
            model_name="license",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="'licenses' or 'publicdomain'",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="license_url",
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="plain_text_url",
            field=models.URLField(default=None, null=True),
        ),
    ]
