# Generated by Django 2.2.20 on 2021-05-25 20:08

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0011_auto_20201111_1256"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalcode",
            options={"ordering": ["license", "language_code"]},
        ),
        migrations.RemoveField(
            model_name="license",
            name="license_class_url",
        ),
        migrations.AddField(
            model_name="license",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="'licenses' or 'publicdomain'",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="license_url",
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="plain_text_url",
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="legalcode",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="License title in this language, e.g. 'Attribution-NonCommercial-NoDerivs 3.0 Unported'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="about",
            field=models.URLField(
                help_text="The license's unique identifier, e.g. 'https://creativecommons.org/licenses/by-nd/2.0/br/'",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="creator_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="E.g. https://creativecommons.org",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_code",
            field=models.CharField(
                help_text="shorthand representation for which class of licenses this falls into. E.g. 'by-nc-sa', or 'MIT', 'nc-sampling+', 'devnations', ...",
                max_length=40,
            ),
        ),
    ]
