# Generated by Django 3.2.19 on 2023-09-01 18:48

# Third-party
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Django langauge code (lowercase IETF"
                        " language tag)",
                        max_length=15,
                    ),
                ),
                (
                    "html_file",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTML file we got this from",
                        max_length=300,
                        verbose_name="HTML file",
                    ),
                ),
                (
                    "translation_last_update",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="The last_updated field from Transifex for"
                        " this translation",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tool title in this language, ex."
                        " 'Atribución/Reconocimiento 4.0 Internacional'",
                        max_length=112,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True, default="", verbose_name="HTML"
                    ),
                ),
                (
                    "legal_code_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Legal Code URL"
                    ),
                ),
                (
                    "deed_url",
                    models.URLField(unique=True, verbose_name="Deed URL"),
                ),
                (
                    "plain_text_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Plain text URL"
                    ),
                ),
            ],
            options={
                "ordering": ["tool", "language_code"],
            },
        ),
        migrations.CreateModel(
            name="TranslationBranch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=40)),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Django langauge code (lowercase IETF"
                        " language tag)",
                        max_length=15,
                    ),
                ),
                (
                    "last_transifex_update",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Time when last updated on Transifex.",
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "legal_codes",
                    models.ManyToManyField(to="legal_tools.LegalCode"),
                ),
            ],
            options={
                "verbose_name_plural": "translation branches",
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        default="",
                        help_text="The tool's unique identifier, ex. "
                        "'https://creativecommons.org/licenses/by-nd/2.0/br/'",
                        unique=True,
                        verbose_name="Base URL",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="shorthand representation for which class of"
                        " tools this falls into. Ex. 'by-nc-sa', or 'MIT',"
                        " 'nc-sampling+', 'devnations', ...",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex. '4.0'. Not required.",
                        max_length=3,
                    ),
                ),
                (
                    "jurisdiction_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="legal jurisdiction (usually a ISO 3166-1"
                        " alpha-2 country code)",
                        max_length=9,
                    ),
                ),
                (
                    "creator_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Ex. https://creativecommons.org",
                        verbose_name="Creator URL",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'licenses' or 'publicdomain'",
                        max_length=13,
                    ),
                ),
                (
                    "deprecated_on",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="if set, the date on which this tool was"
                        " deprecated",
                        null=True,
                    ),
                ),
                ("deed_only", models.BooleanField(default=False)),
                (
                    "permits_derivative_works",
                    models.BooleanField(default=None),
                ),
                ("permits_reproduction", models.BooleanField(default=None)),
                ("permits_distribution", models.BooleanField(default=None)),
                ("permits_sharing", models.BooleanField(default=None)),
                ("requires_share_alike", models.BooleanField(default=None)),
                ("requires_notice", models.BooleanField(default=None)),
                ("requires_attribution", models.BooleanField(default=None)),
                (
                    "prohibits_commercial_use",
                    models.BooleanField(default=None),
                ),
                (
                    "prohibits_high_income_nation_use",
                    models.BooleanField(default=None),
                ),
                (
                    "is_replaced_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="A related resource that supplants,"
                        " displaces, or supersedes the described resource"
                        " (dcterms:isReplacedBy)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="legal_tools.tool",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="A related resource from which the described"
                        " resource is derived (dcterms:source)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_of",
                        to="legal_tools.tool",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "unit", "jurisdiction_code"],
            },
        ),
        migrations.AddField(
            model_name="legalcode",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_codes",
                to="legal_tools.tool",
            ),
        ),
    ]
