# Generated by Django 4.2.23 on 2026-01-09 15:12

# Third-party
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalcode",
            name="markdown",
            field=models.TextField(
                blank=True, default="", verbose_name="Markdown"
            ),
        ),
    ]
